# Generated by Django 4.0.5 on 2022-12-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        ('dividends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='portfolioId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.portfolio'),
        ),
    ]
