# Generated by Django 4.0.5 on 2022-12-24 14:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.UUIDField(default=uuid.uuid4)),
                ('symbol', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('logo_url', models.CharField(default='none', max_length=255)),
                ('sector', models.CharField(default='none', max_length=255)),
                ('company_desc', models.TextField()),
                ('website', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('lastDiv', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('exchange', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolioId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=255)),
            ],
        ),
    ]
