# Generated by Django 4.0.5 on 2022-12-24 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.UUIDField(default=uuid.uuid4)),
                ('symbol', models.CharField(max_length=255)),
                ('timestamp', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shares', models.DecimalField(decimal_places=2, max_digits=9)),
                ('portfolioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.portfolio')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
